# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            .×‘
tagline:          'topics in functional programming'
description:      'topics in functional programming'
url:              http://baruchel.github.io
baseurl:          /

author:
  name:           'Thomas Baruchel'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/baruchel
